### ISSUE TITLE
maybe a bug?

### ISSUE THREAD

**Issue by dspforcom** [XBQ314/Number-theoretic-transform-NTT-radix-2-parallelism-2-on-FPGA#1]
It seems that the modular addition and modular subtraction modules are incorrect. The method of determining overflow by examining the highest bit is only applicable when the modulus is a power of two. However, in the NTT (Number Theoretic Transform), the modulus is definitely a prime number.

**Comment by XBQ314** [comment]
Have you tried the tb_ma()? The _p is equal to ~P+1'b1, in which the P is the modulus. The modular addition is right under this configuration.

**Comment by dspforcom** [comment]
Oh, I get it. Thanks a ton for your support :)
